[project]
requires-python = ">=3.6"
name = "tweedledum"
version = "1.1.2"

description = "tweedledee"

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cmake>=3.18",
    "ninja",
    "scikit-build>=0.12.0",
]
